version: 2.1
jobs:
  build:
    working_directory: /go/src/github.com/Worldremit/terraform-provider-kafka
    docker:
      - image: circleci/golang:1.13
        environment:
          TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: go build .
      - store_artifacts:
          path: /go/src/github.com/Worldremit/terraform-provider-kafka/terraform-provider-kafka
          destination: terraform-provider-kafka

  test:
    working_directory: /go/src/github.com/Worldremit/terraform-provider-kafka
    docker:
      - image: circleci/golang:1.13
        environment:
          TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - setup_remote_docker
      - run: make test
      - run: go get github.com/jstemmer/go-junit-report
      - run: mkdir -p $TEST_RESULTS
      - run:
          name: Run Tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            docker-compose -f docker-compose.yaml -f docker-compose.testacc.yaml up \
              --abort-on-container-exit testacc | tee ${TEST_RESULTS}/go-test.out
      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test
